In [10]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import math
import scipy as scp

In [2]:
n_obs = 5
b_exp = 1.8

In [26]:
# direct formula implementation
def pval_bkg_only(n_obs, b_exp):
    p = 0.0
    for i in range(0, n_obs):
        p += ((b_exp**i)/((math.factorial(i)))*math.exp(-b_exp))
    return 1-p

In [27]:
pval_bkg_only(n_obs, b_exp)

0.03640666100108336

In [28]:
# scipy short-cut
1-scp.stats.poisson.cdf(4,1.8)

0.036406661001083473

In [30]:
# 3-sigma
p3s = 1-0.997
p3s

0.0030000000000000027

The p-value is larger than the 3 sigma value. This means the excess is not significant.

In [31]:
def pval_sig_plus_bkg(n_obs, b_exp, s_exp):
    p = 0.0
    for i in range(0,n_obs+1):
        p += ((b_exp+s_exp)**i)/(math.factorial(i))*math.exp(-(b_exp+s_exp))
    return p

In [38]:
s_exp_max = np.linspace(0,10,11)

for k in s_exp_max:
    #print("self-defined function: ", pval_sig_plus_bkg(n_obs,b_exp,k))
    #print("scipy short-cut: ", scp.stats.poisson.cdf(5,1.8+k))
    print("expected s: ", k, "\t p-val: ", scp.stats.poisson.cdf(5,1.8+k))

expected s:  0.0 	 p-val:  0.9896219631338404
expected s:  1.0 	 p-val:  0.934889686635759
expected s:  2.0 	 p-val:  0.8155562560569335
expected s:  3.0 	 p-val:  0.6510064372694917
expected s:  4.0 	 p-val:  0.47831468715817593
expected s:  5.0 	 p-val:  0.3269771300718833
expected s:  6.0 	 p-val:  0.21025110554874318
expected s:  7.0 	 p-val:  0.12838664508882555
expected s:  8.0 	 p-val:  0.07504113738341638
expected s:  9.0 	 p-val:  0.04225517364020971
expected s:  10.0 	 p-val:  0.023043101774884243


5% is somewhere between 8 and 9 events. Fine-tune the search there:

In [39]:
s_exp_max = np.linspace(8,9,11)

for k in s_exp_max:
    print("expected s: ", k, "\t p-val: ", scp.stats.poisson.cdf(5,1.8+k))

expected s:  8.0 	 p-val:  0.07504113738341638
expected s:  8.1 	 p-val:  0.07096514087048697
expected s:  8.2 	 p-val:  0.06708596287903189
expected s:  8.3 	 p-val:  0.06339596386834864
expected s:  8.4 	 p-val:  0.05988765537102165
expected s:  8.5 	 p-val:  0.05655370984090572
expected s:  8.6 	 p-val:  0.053386969043626664
expected s:  8.7 	 p-val:  0.05038045108893583
expected s:  8.8 	 p-val:  0.04752735620150341
expected s:  8.9 	 p-val:  0.04482107132365227
expected s:  9.0 	 p-val:  0.04225517364020971


5% is somewhere between 8.7 and 8.8 events. Fine-tune the search there:

In [40]:
s_exp_max = np.linspace(8.7,8.8,11)

for k in s_exp_max:
    print("expected s: ", k, "\t p-val: ", scp.stats.poisson.cdf(5,1.8+k))

expected s:  8.7 	 p-val:  0.05038045108893583
expected s:  8.709999999999999 	 p-val:  0.05008834815427274
expected s:  8.719999999999999 	 p-val:  0.04979777259804961
expected s:  8.73 	 p-val:  0.049508717740923115
expected s:  8.74 	 p-val:  0.04922117692231874
expected s:  8.75 	 p-val:  0.048935143500466564
expected s:  8.76 	 p-val:  0.04865061085244038
expected s:  8.77 	 p-val:  0.04836757237419089
expected s:  8.780000000000001 	 p-val:  0.04808602148058197
expected s:  8.790000000000001 	 p-val:  0.04780595160542332
expected s:  8.8 	 p-val:  0.04752735620150341


5% is somewhere between 8.71 and 8.72 events. Fine-tune the search there:

In [41]:
s_exp_max = np.linspace(8.71,8.72,11)

for k in s_exp_max:
    print("expected s: ", k, "\t p-val: ", scp.stats.poisson.cdf(5,1.8+k))

expected s:  8.71 	 p-val:  0.05008834815427272
expected s:  8.711 	 p-val:  0.05005922197697671
expected s:  8.712000000000002 	 p-val:  0.05003011106676179
expected s:  8.713000000000001 	 p-val:  0.05000101541694229
expected s:  8.714 	 p-val:  0.04997193502083388
expected s:  8.715 	 p-val:  0.049942869871754565
expected s:  8.716000000000001 	 p-val:  0.04991381996302396
expected s:  8.717 	 p-val:  0.0498847852879639
expected s:  8.718 	 p-val:  0.04985576583989758
expected s:  8.719000000000001 	 p-val:  0.049826761612150244
expected s:  8.72 	 p-val:  0.049797772598049524


5% is somewhere between 8.713 and 8.714 events. Fine-tune the search there:

In [42]:
s_exp_max = np.linspace(8.713,8.714,11)

for k in s_exp_max:
    print("expected s: ", k, "\t p-val: ", scp.stats.poisson.cdf(5,1.8+k))

expected s:  8.713 	 p-val:  0.05000101541694232
expected s:  8.713099999999999 	 p-val:  0.04999810669102477
expected s:  8.713199999999999 	 p-val:  0.049995198117637606
expected s:  8.7133 	 p-val:  0.04999228969677415
expected s:  8.7134 	 p-val:  0.049989381428427807
expected s:  8.7135 	 p-val:  0.04998647331259182
expected s:  8.7136 	 p-val:  0.04998356534925956
expected s:  8.7137 	 p-val:  0.04998065753842439
expected s:  8.7138 	 p-val:  0.04997774988007933
expected s:  8.7139 	 p-val:  0.04997484237421816
expected s:  8.714 	 p-val:  0.04997193502083388


In [43]:
# look at the difference between the p-values for lambda_s = 8.713 and 8.714

scp.stats.poisson.cdf(5,1.8+8.713) - scp.stats.poisson.cdf(5,1.8+8.7131)

2.908725917634414e-06

This difference is smaller than 10^⁻5 --> therefore lambda_s_max is 8.713

In [45]:
dist = np.random.poisson((1.8+8.713), 10000000)  #MC with signal equal to 95% CL limit

In [47]:
count = 0
for i in range(len(dist)):
    if dist[i] < 6:
        count +=1 # count cases with n <= n_obs --> should by ~5% by construction
print(str(count/len(dist) * 100) + "%")


4.98935%
